name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move files from src to root
        run: |
          mv src/* .
          rm -rf src

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-deploy GitHub Pages" || echo "No changes to commit"
          git push https://$GITHUB_TOKEN@github.com/RobertoAArevalo/personal_website.git main
